services:
  mariadb:
    image: mariadb:10.6
    container_name: litecore-mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uadmin",
          "-padmin123",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  litecore:
    image: chacoxxx/fineract-ai-asistant:core
    container_name: litecore
    restart: unless-stopped

    depends_on:
      mariadb:
        condition: service_healthy

    ports:
      - "8443:8443"

    environment:
      SERVER_PORT: 8443

      LITECORE_HIKARI_DRIVER_SOURCE_CLASS_NAME: org.mariadb.jdbc.Driver
      LITECORE_HIKARI_JDBC_URL: jdbc:mariadb://mariadb:3306/litecore_tenants
      LITECORE_HIKARI_USERNAME: admin
      LITECORE_HIKARI_PASSWORD: admin123

      LITECORE_DEFAULT_TENANTDB_HOSTNAME: mariadb
      LITECORE_DEFAULT_TENANTDB_PORT: 3306
      LITECORE_DEFAULT_TENANTDB_UID: admin
      LITECORE_DEFAULT_TENANTDB_PWD: admin123

  #admin:
  #  image: chacoxxx/fineract-ai-asistant:admin
  #  ports:
  #    - "4201:4201"
  #  environment:
  #    - LITECOREBACK_API_URLS=http://localhost:8443
  #    - LITECOREBACK_API_URL=http://localhost:8443
  #    - LITECOREBACK_API_PROVIDER=/litecore-provider/api
  #    - LITECOREBACK_API_VERSION=/v1
  #    - LITECOREBACK_PLATFORM_TENANT_IDENTIFIER=default
  #    - LITECORE_DEFAULT_LANGUAGE=es-MX
  #    - LITECORE_SUPPORTED_LANGUAGES=cs-CS,de-DE,en-US,es-MX,fr-FR,it-IT,ko-KO,lt-LT,lv-LV,ne-NE,pt-PT,sw-SW
  #    - LITECORE_SESSION_IDLE_TIMEOUT=300000

volumes:
  mariadb_data:
